spring.application.name=keycloak_kotlin

server.port=8080
server.servlet.context-path=/keycloak/api

logging.level.root = info
logging.level.vitos.local.keycloak_kotlin = info
logging.level.vitos.local.keycloak_kotlin.services = debug
logging.level.vitos.local.keycloak_kotlin.migration = debug

##--------------------- POSTGRES DATASOURCE --------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/mcspdb
spring.datasource.username=postgres
spring.datasource.password=Vitalex88
spring.datasource.driver-class-name=org.postgresql.Driver
##--------------------- POSTGRES DATASOURCE --------------------------------------------------------------------------

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=keycloakadp
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------
keycloak.server.url=http://localhost:8443

keycloak.master.admin.realm=master
keycloak.master.admin.client-id=admin-client
keycloak.master.admin.secret=TapOEMvNpD4ZajAcAzdXQriUNYHjzRNt

keycloak.admin.realm=SpringBootKeycloak
keycloak.admin.client_id=login-admin
keycloak.admin.client_secret=6dMULRFc4gnadbs4xaqzvUueaQNJJSBS

spring.security.oauth2.client.registration.keycloak.client-id=login-web
spring.security.oauth2.client.registration.keycloak.client-secret=WbP46pdXfGG1Gmpw5sS859vL5NgLN2t4
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}/protocol/openid-connect/certs
##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------

##--------------------- SWAGGER UI------------------------------------------------------------------------------------
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.writer-with-default-pretty-printer=true

#springdoc.enable-hateoas=false
#springdoc.enable-data-rest=false
##--------------------- SWAGGER UI------------------------------------------------------------------------------------

digital.ruble.pcrconnect.callback.login=alex
digital.ruble.pcrconnect.callback.password=alex

dormant.delete.last-enter-time-period=48
dormant.delete.ft-userdel-event=true
